# Generated by Django 2.2.1 on 2019-07-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190711_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('admin', models.IntegerField(default=0, max_length=10)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
    ]
