# Generated by Django 2.2.1 on 2019-07-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=0),
        ),
    ]
